### PR TITLE
Allow choosing a different language for Azure speech-to-text

### PR DESCRIPTION
**Pull request by Zerodya**
This will allow non-english people to talk to USAW in their native language (as long as it's supported by the Azure speech-to-text service)

### CODE REVIEW

**Comment by lookingforaCTO** [comment]
@hackdaddy8000 how can we implement this to the waifu ai

**Comment by Zerodya** [comment]
> @hackdaddy8000 how can we implement this to the waifu ai

By using the `stt_language` URL parameter.
For example to talk to her in english add `&stt_language=en-US` at the end of the URL. 
Use a different language code depending on your spoken language.

**Comment by lookingforaCTO** [comment]
do you know how to change the character of others generated by ourselves elsewhere? i am not a programmer and don't understand, need someone to help me with this and a project alike, if you can?

**Comment by Zerodya** [comment]
I'm not sure I understand your question correctly but you should probably open a new issue for that.

**Pull request merged**
